[workspace]

[[package]]
name = "inline_csharp_demo"
publish = false
changelog_update = false
git_release_enable = false

[[package]]
name = "inline_csharp_core"
changelog_update = false

[[package]]
name = "inline_csharp_macros"
changelog_update = false

[[package]]
name = "inline_csharp"
changelog_update = true
